### ISSUE TITLE
add BLS aggregated signatures support 

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/sgxwallet#400]

**Comment by PolinaKiporenko** [comment]
https://github.com/skalenetwork/internal-support/blob/main/docs/specifications/cryptography/bls-aggregated-signatures.md

**Comment by DmytroNazarenko** [comment]
[1.9.0-beta.0](https://github.com/skalenetwork/sgxwallet/releases/tag/1.9.0-beta.0)

**Comment by EvgeniyZZ** [comment]
Not require testing afford
