### ISSUE TITLE
Add support of Ubuntu 20.04

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/sgxwallet#404]
* PRD: SYSTEM UPGRADE

Add support of Ubuntu 20.04 for sgxwallet to migrate to the new type of instances.
* Check Ubuntu 20.04 compatibility for sgxwallet and backward compatibility with 18.04
* Update sgxwallet to support new ubuntu 20.04 and to have backward compatibility with 18.04
* Sign new secure enclave binary on the new OS version

**Comment by DmytroNazarenko** [comment]
[1.9.0-beta.0](https://github.com/skalenetwork/sgxwallet/releases/tag/1.9.0-beta.0)

**Comment by OleksanderSalamatov** [comment]
Approved
SGX: sgxwallet:1.9.0-beta.0
Testrun: R183 in SGX project
Tested new container on Ubuntu 18.04 and Ubuntu 20.04 servers, with Ubuntu 18.04 and Ubuntu 20.04 nodes and SGX remains fully backward-compatible, no SGX-related errors were spotted during testing
