### ISSUE TITLE
Unclear building instruction

### ISSUE THREAD

**Issue by 20urc3** [skalenetwork/sgxwallet#424]
**Describe the bug**
The instruction to build the project are not clear. 
If we follow 
```
git clone -b sgx_2.13 --depth 1 https://github.com/intel/linux-sgx
cd linux-sgx
make preparation
sudo make sdk_install_pkg_no_mitigation
cd /opt/intel
sudo sh -c 'echo yes | /linux-sgx/linux/installer/bin/sgx_linux_x64_sdk_*.bin'
sudo make psw_install_pkg
sudo cp /linux-sgx/linux/installer/bin/sgx_linux_x64_psw*.bin .
sudo ./sgx_linux_x64_psw*.bin --no-start-aesm
```
It won't compile with OpenSSL 3.0 or any recent version.
Even with using a workaround (downgrading OpenSSL) it's not working.
Results in: checking whether the C compiler works... no

Could you please update/provide a clear step-by-step to build the sgxwallet?

Thanks!

**Comment by 20urc3** [comment]
here the exact method to build the sdk:
https://github.com/intel/linux-sgx
The first part is missing from your guide (dependencies & all)

**Comment by olehnikolaiev** [comment]
hello @20urc3 ! thanks for your submission! our building instructions are outdated and will be updated as soon as possible.
meanwhile you can follow the steps from this file https://github.com/skalenetwork/sgxwallet/blob/develop/DockerfileBase that we use to build the docker container for our product.
