### ISSUE TITLE
Can't start new SGX because of segmentation fault

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/sgxwallet#426]
Preconditions:
Vultr server: E3-1270, 32Gb RAM, Ubuntu 20.04 (Clean reinstall)
SGX enabled (hardware mode), driver set up, sgx devices present in /dev
SGX versions: sgxwallet_release:1.9.0-stable.0 (signed enclave), sgxwallet:1.9.0-beta.1

Steps:
Default setup steps from sgx admin documentation

Container starts, but restarting because of `sgx_create_enclave_search failed secure_enclave.signed.so 2` error, which is `SGX_ERROR_INVALID_PARAMETER  = SGX_MK_ERROR(0x0002),  -   The parameter is incorrect `

[Log of startup](https://github.com/skalenetwork/sgxwallet/files/12738213/sgxlog.txt)

**Comment by OleksanderSalamatov** [comment]
Still same error on `1.9.0-stable.1` version of container

**Comment by olehnikolaiev** [comment]
the issue was resolved by downgrading to older kernel version.
